4 build ux/UI for list events
Jan-OkeMettendorf/simple-sports-club pull request #31
Opened 2021-11-03 12:41 UTC by Jan-OkeMettendorf

First implementation of the graphical layout of the app completed. Extension of the page for displaying groups is done. Groups are displayed via a JSON file. Implementation of backend not yet done and will be mapped when UserStory 5 is completed. Entry into detail page (UserStory 5) of a group already prepared.

2021-11-03 13:28 UTC, macben888 approved these changes

2021-11-03 13:30 UTC, macben888 requested changes
change the jdk version in your *.yml file to match the project's jdk version

2021-11-03 14:19 UTC, christophersiem approved these changes
Like the design! Left a few comments 🙌🏽

2021-11-03 14:19 UTC, christophersiem commented on frontend/src/components/Header.js
> +  height: 30px;
check if you really need to set those values

2021-11-03 14:19 UTC, christophersiem commented on frontend/src/components/groups.json
> +        "mobilNumber": null,
```suggestion
        "mobileNumber": null,
```

2021-11-03 14:19 UTC, christophersiem commented on frontend/src/components/groups.json
> +        "mobilNumber-hidden": true,
```suggestion
        "mobileNumber-hidden": true,
```

2021-11-03 14:19 UTC, christophersiem commented on frontend/src/components/groups.json
> +        "LastName": "Mettendorf",
```suggestion
        "lastName": "Mettendorf",
```

2021-11-03 14:19 UTC, christophersiem commented on frontend/src/components/groups.json
> +    "CountOfMember": 12,
```suggestion
    "countOfMember": 12,
```

2021-11-03 14:19 UTC, christophersiem commented on frontend/src/components/Sidebar.js
> +const StyledNavLink = styled(NavLink)`
i think you don't need to set `display : flex` repeatedly, pls check if you can leave it away

2021-11-03 14:19 UTC, christophersiem commented on frontend/src/App.js
> +        <GlobalStyle/>
Good idea to use a `GlobalStyle`, but seems like you don't use it yet :)

2021-11-04 14:01 UTC, Jan-OkeMettendorf commented on frontend/src/components/NavBar.js
> +    }
done! Thank you! :)

2021-11-04 21:25 UTC, Jan-OkeMettendorf commented on frontend/src/components/Groups-data.js
> +        </>
done! thank you! :)

2021-11-04 21:37 UTC, Jan-OkeMettendorf commented on frontend/src/components/Sidebar.js
> +const StyledNavLink = styled(NavLink)`
I think I need to set display : flex to get the right gap between the icon and the corresponding texts

2021-11-04 21:58 UTC, merged